<<<<<<< HEAD
\c postgres;

DROP DATABASE IF EXISTS qa;

CREATE DATABASE qa;

\c qa;

-- ---
-- Table 'Questions'
--
-- ---

DROP TABLE IF EXISTS questions;

CREATE TABLE questions (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "product_id" INTEGER NOT NULL DEFAULT NULL,
  "question_body" VARCHAR(1000) NOT NULL DEFAULT 'NULL',
  "question_date" VARCHAR(250) NULL DEFAULT NULL,
  "asker_name" VARCHAR(250) NOT NULL DEFAULT 'NULL',
  "asker_email" VARCHAR (250) NOT NULL DEFAULT 'NULL',
  "reported" BOOLEAN NOT NULL DEFAULT false,
  "question_helpfulness" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

-- ---
-- Table 'Answers'
--
-- ---

DROP TABLE IF EXISTS answers;

CREATE TABLE answers (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "question_id" INTEGER REFERENCES questions("id"),
  "body" VARCHAR(1000) NOT NULL DEFAULT 'NULL',
  "date" VARCHAR(250) NOT NULL DEFAULT 'NULL',
  "answerer_name" VARCHAR (250) NOT NULL DEFAULT 'NULL',
  "answerer_email" VARCHAR (250) NOT NULL DEFAULT 'NULL',
  "reported" BOOLEAN NOT NULL DEFAULT false,
  "helpfulness" INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

-- ---
-- Table 'Photos'
--
-- ---

DROP TABLE IF EXISTS photos;

CREATE TABLE photos (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "answer_id" INTEGER REFERENCES answers("id"),
  "url" VARCHAR NOT NULL DEFAULT 'NULL',
  PRIMARY KEY ("id")
);

\copy questions(id, product_id, question_body, question_date, asker_name, asker_email, reported, question_helpfulness) FROM './data/questions.csv' DELIMITER ',' CSV HEADER;

\copy answers(id, question_id, body, "date", answerer_name, answerer_email, reported, helpfulness ) FROM './data/answers.csv' DELIMITER ',' CSV HEADER;

\copy photos(id, answer_id, "url") FROM './data/answers_photos.csv' DELIMITER ',' CSV HEADER;


-- ---
-- Foreign Keys
-- ---

-- ALTER TABLE answers ADD FOREIGN KEY (id_questions) REFERENCES questions ("id");
-- ALTER TABLE photos ADD FOREIGN KEY (id_answers) REFERENCES answers ("id");

